allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    project.buildDir = layout.buildDirectory.dir("${rootProject.layout.buildDirectory.get()}/${project.name}").get().asFile
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
