android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Dfile.encoding=UTF-8
systemProp.https.protocols=TLSv1.2
systemProp.jdk.tls.client.protocols=TLSv1.2
